### ISSUE TITLE
Struggling to get user token

### ISSUE THREAD

**Issue by SylCard** [mental32/spotify.py#11]
Hi Mental32, I've been trying to access my personal spotify data using your top_tracks example. I have a client set up and I understand that I need some user token (user = await client.user_from_token("sometoken"). How can I obtain this token easily, without building some ui?

Thanks for your time

**Comment by mental32** [comment]
You will have to spin a webserver and follow an OAuth2 flow, please see the [spotify authorization guide](https://developer.spotify.com/documentation/general/guides/authorization-guide/) for more details.
