### ISSUE TITLE
Feature Idea - Pass limit=None to get all playlists, tracks, ...

### ISSUE THREAD

**Issue by micahdlamb** [mental32/spotify.py#22]
When I call user.get_playlists() and user.library.get_tracks() I need all the playlists/tracks but it currently limits me to getting 50 at a time.

It would be nice if I could pass limit=None to get them all at once.  I'll make a pull request if you think its worth doing.

**Comment by mental32** [comment]
Normally the way to do this would be a `obj.get_all_{blank}` method, but I've just noticed thanks to you that `User`and `Library` do not implement these complimentary methods.

I'd like to add:
 - `User.get_all_playlists()`
 - `Library.get_all_tracks()`
 - `Library.get_all_albums()`

And perhaps `obj.total_{blank}` methods as seen on `Artist.total_albums()`

Perhaps a better design as you pointed out would be to allow passing `None` as the `limit` argument where then the Spotify paginated object will be exhausted. Of course if this will be the case then the `/examples` usages need to be updated.

@micahdlamb I can implement this now and get a pypi release up (would be version `0.7.0`) or are you keen on PR'ing this yourself?

**Comment by micahdlamb** [comment]
I'd love if you do it :)  Thanks so much!

**Comment by micahdlamb** [comment]
I think I prefer just keeping a separate get_all_tracks() function.  Its clear how to get all tracks when you see the get_all_tracks function in the intelliense.

**Comment by mental32** [comment]
Right, I'll go ahead and add the above mentioned methods, I'll ping you when they're in?

**Comment by mental32** [comment]
These methods have been added in `v0.7.0` which is merged into master
