### ISSUE TITLE
Makefile install fails

### ISSUE THREAD

**Issue by winston-yallow** [mental32/spotify.py#32]
The `make install` command still uses the setup.py file which was replaced by the pyproject.toml. I do know that the correct way to install this is with `pip3 install -U .`

_(This is not really important, I just find it weird that the makefile references an obsolete file.)_

**Comment by winston-yallow** [comment]
It looks like the command listed in the readme is `pip3 -U install .` while the correct one probably is `pip3 install -U .` 

I could make a PR changing the Readme and the makefile to the correct command?

**Comment by mental32** [comment]
That Makefile wasn't intended to be used by anyone who wasn't developing, its a sort of makeshift toolchain that I threw together that helps me out.

If you're keen on pr'ing this I'm happy to merge :)

**Comment by winston-yallow** [comment]
Ignore the closed pr that referenced this issue, I made it by accident. The pr #33 is the correct one

**Comment by mental32** [comment]
@winston-yallow No worries, happens to the best of us :)
