### ISSUE TITLE
Token refreshing issue

### ISSUE THREAD

**Issue by micahdlamb** [mental32/spotify.py#35]
I am doing something similar to your "Usage with flask" example where I store User objects in a dict for an indefinite period of time.  I've been using the refresh=True option to automatically refresh the token (which works) but it doesn't seem good to me that it is continuously refreshing the token forever when I'm not making any requests with the user.   This is especially bad if I create multiple copies of the User object which all keep refreshing.  Ultimately, I don't think I should be storing Users in a dict forever but that's another discussion which I believe mikonse's pull request is trying to address.

My thought is that it would make more sense if you handled the token expiration in HttpClient.request by catching the exception:
**spotify.errors.HTTPException: Unauthorized (status code: 401): The access token expired**
refreshing and retrying the request (just like you are doing for several other exceptions).  I saw it done this way in some other oauth implementations too.

When I looked at the HttpClient.request code I was surprised to see you are actually handling 401 and calling self.get_bearer_info().  However, I'm not sure what that function is supposed to be doing... It doesn't take the code, token or refresh_token as input.  I'm pretty sure its not working because the 401 exception just keeps happening RETRY_AMOUNT times before raising out of the loop.

**Comment by micahdlamb** [comment]
I hope that makes sense... I'd be happy to do a pull request.  In order to do that I need to know if there is some other usecase HttpClient.get_bearer_info is handling (besides refreshing the token) or is the function just broken.

**Comment by micahdlamb** [comment]
I created a commit here to explain what I'm trying to say. 
 https://github.com/micahdlamb/spotify.py/commit/2a62f2208c9ce62b187b24c07d501d7802052156

This seems like a better way to handle the token refreshing. Its a lot simpler and doesn't continually refresh the token when I hold onto User objects for a long time.

I'm not making a pull request as there are api breaking changes and I'm not sure how you would want to handle that.  Let me know what you think...

**Comment by mental32** [comment]
Nice catch!

I was under the impression that refresh tokens expired after some time, but I just checked the Spotify web API guides and I see no mention of this.

This is certainly a much cleaner solution to handling User access token refreshing.

> I'm not making a pull request as there are api breaking changes and I'm not sure how you would want to handle that. Let me know what you think...

The library is semantically versioned and currently it hasn't reached major revision one yet (its still at major zero) so breaking changes are perfectly fine until then.

Would you like to PR this in?
I'll likely do it tomorrow otherwise :)

**Comment by micahdlamb** [comment]
Great!  I'll try to make a pull request tonight.
