### ISSUE TITLE
'Payload' referenced before assignment

### ISSUE THREAD

**Issue by Skeletrox** [mental32/spotify.py#41]
`UnboundLocalError: local variable 'payload' referenced before assignment` is thrown when attempting to get a track from ID.

Further research into the source code points the error at line 1597 in track, where if market is not defined the payload variable isn't created.

**Comment by mental32** [comment]
@Skeletrox could you send the full traceback in a hastebin/pastebin post.

Also what version of spotify.py are you running.

**Comment by Skeletrox** [comment]
The pastebin URL is [https://pastebin.com/XxTUwJPC](https://pastebin.com/XxTUwJPC).

The spotify version I use is `0.8.1` installed from PyPi through `pip3 install -U spotify`.

**Comment by mental32** [comment]
Thanks for the traceback, I've fixed this but it's not on pypi right now, I'll be publishing changes there later.
