### ISSUE TITLE
How to do get genre_tag of a song/track ?

### ISSUE THREAD

**Issue by Priyansh2** [mental32/spotify.py#5]
Hi. I am Priyansh. I just now installed the library and wanted to extract genre for a given song/track name as input (search query). I cannot see anywhere the functionality to get genre tags for a track.
We can do the same for album but not for track. Is your implementation complete or spotify doesn't provide the genre info. of track ? Meanwhile I find a bug in the api docs. The `genres` attribute should changed to `genre` for the album class else it will give the error

**Comment by mental32** [comment]
Spotify doesn't provide genres for specific tracks, only artists and albums.

You could get the genre from the album of a track `track.album.genres`
