### ISSUE TITLE
Can't use parameters with user.top_artists()

### ISSUE THREAD

**Issue by drowe-official** [mental32/spotify.py#50]
Regardless of what parameters you set for user.top_artists(), such as:

`**user.top_artists(limit=50,offset=0, time_range="long_term")**`

You'll still get the default limit, offset and time range regardless of what you set the params to.
I managed to fix it locally by fiddling around with the library. I believe the problem is that the payload in the function top_artists_or_tracks(), is not sent the HTTP request.

I fixed it by changing line 854 in http.py from
`return self.request(route)`
to 
`return self.request(route, params=payload)`

I'd make a pull request but I'm new at this stuff.

**Comment by mental32** [comment]
@drowe4 Thanks for reporting this! I can reproduce and will be pushing a fix soon to both Github and PyPI :)

**Comment by mental32** [comment]
Fixed by: https://github.com/mental32/spotify.py/commit/adee6d2a3c1403ff3185269cc5b4058f16e78fe4
