### ISSUE TITLE
Suggestion: allow User.recently_played() to take same optional parameters as Http.recently_played()

### ISSUE THREAD

**Issue by iangu48** [mental32/spotify.py#54]
Hi it's me again

I was hoping you could allow the recently_played() function in the User class to use the full extent of the function in http.py. Right now, User.recently_played() doesn't take any parameters but HTTPClient.recently_played() is as follows

recently_played(*, limit: Optional[int] = 20, before: Optional[str] = None, after: Optional[str] = None) → Awaitable[T_co]

**Comment by mental32** [comment]
I see no reason not to!
I'm going to have to hold off on this until tomorrow however since its late here (GMT) :owl:
