### ISSUE TITLE
Not possible to install spotify.py and pyspotify at the same time

### ISSUE THREAD

**Issue by jodal** [mental32/spotify.py#66]
Hi, I'm one of the maintainers of [Mopidy](https://mopidy.com) and [pyspotify](https://pypi.org/project/pyspotify/).

After debugging with a Mopidy user recently, we found that their installation of Mopidy-Spotify, which is using pyspotify, was weirdly broken because the users also had spotify.py installed. The problem is that both projects use the `spotify` name for the top-level Python package, which makes it impossible to install both projects at the same time.

As pyspotify predates spotify.py by about eight years, I would very much appreciate it if you considered renaming your top-level package to something else than `spotify`, e.g. to `spotifypy`.

Thanks!

**Comment by mental32** [comment]
> which makes it impossible to install both projects at the same time.

I suggest you advise your user to uninstall spotify.py from any global or user wide package site and to only have it installed under a venv where the conflict wont arise, this project has effectively been unmaintained for a while now so I don't see the point in changing the name.
