### ISSUE TITLE
Player.command: Device not found.

### ISSUE THREAD

**Issue by ghost** [mental32/spotify.py#7]
If I supply or don't supply the `device` parameter to Player.pause, resume, play etc. The error device not found is thrown.
It is strange as just before that, I perform `user.get_devices()` and retrieve the `Spotify.Device` object, which I pass directly to the parameter.

Full traceback:
```
  File "spotiterm.py", line 54, in main
    options[input(green("Select Option: "))](client, user)
  File "/Users/github/SpotiTerm-Rewrite/general.py", line 181, in player
    options[input(green("Select Option: "))](chosen_device, _player, user)
  File "/Users//github/SpotiTerm-Rewrite/general.py", line 154, in controls
    _player.pause()
  File "/Users//.local/share/virtualenvs/SpotiTerm-Rewrite-5Ht0qwiq/lib/python3.7/site-packages/spotify/sync/models.py", line 42, in wrapper
    func(self, *args, **kwargs)
  File "/Users/.local/share/virtualenvs/SpotiTerm-Rewrite-5Ht0qwiq/lib/python3.7/site-packages/spotify/sync/thread.py", line 73, in run_coro
    raise err
  File "/Users//.local/share/virtualenvs/SpotiTerm-Rewrite-5Ht0qwiq/lib/python3.7/site-packages/spotify/models/player.py", line 82, in pause
    await self.user.http.pause_playback(device_id=str(device))
  File "/Users//.local/share/virtualenvs/SpotiTerm-Rewrite-5Ht0qwiq/lib/python3.7/site-packages/spotify/http.py", line 205, in request
    raise NotFound(r, data)
spotify.errors.NotFound: Not Found (status code: 404): Device not found```

**Comment by mental32** [comment]
Spotify details the response format for any player related actions [as such](https://developer.spotify.com/documentation/web-api/reference/player/pause-a-users-playback/#response-format):
> When performing an action that is restricted, 404 NOT FOUND or 403 FORBIDDEN will be returned together with a player error message.

In you particular [case](https://developer.spotify.com/documentation/web-api/reference/object-model/#player-error-reasons):
> For example, if there are no active devices found, the request will return 404 NOT FOUND response code and the reason NO_ACTIVE_DEVICE

And if we lookup what exactly `NO_ACTIVE_DEVICE` means:
> Requires an active device and the user has none.

I don't believe Spotify actually defines what an "active device" is but in my experience, an active device is a device with a Spotify client actively streaming audio.

For you this means that you'd have to check for the presence of an active device, I recommend using the attribute `Player.is_playing`, and depending if one was found specify a device when performing player actions.

**Comment by mental32** [comment]
As for the library error, it looks like you should be able to pass a spotify.Device object directly. As the class does not define a `__str__` its `__repr__` is preferred leading to a bad id used when the api action is performed.

To solve this pass in the device id (`device.id`) with the device kwarg.
