### ISSUE TITLE
Invalid Syntax?

### ISSUE THREAD

**Issue by CipherTheDev** [mental32/spotify.py#8]
```
import spotify
import asyncio

def main():

    client = spotify.Client('SomeID', 'SomeSecret')
    results = await client.search('drake', limit=5, offset=20, market='JP')
    
if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

I get this error:
`SyntaxError: invalid syntax
PS C:\Users\Cipher\Desktop\pythonfiles> python .\spotify.py
  File ".\spotify.py", line 8
    results = await client.search('drake')
                         ^
SyntaxError: invalid syntax
PS C:\Users\Cipher\Desktop\pythonfiles> python .\spotify.py
Traceback (most recent call last):
  File ".\spotify.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File ".\spotify.py", line 7, in main
    client = spotify.Client('SomeID', 'SomeSecret')
AttributeError: module 'spotify' has no attribute 'Client'`

Please note this is my first time posting an issue but most of the code were copied from the examples to get a grasp of the API.

Thank you,

Cipher.

**Comment by CipherTheDev** [comment]
### Update

I managed to fix my issue of ` client = spotify.Client('SomeID', 'SomeSecret')` and i am constantly trying to resolve other issues.
Thanks!

**Comment by mental32** [comment]
The SyntaxError is due to an `await` statement being encountered inside a regular function `def` vs and asynchronous coroutine function `async def`

Also the AttributeError is being caused by you naming the file `spotify.py` which is confusing Python when you actually try to import the library.

Which example did you get this from?

**Comment by CipherTheDev** [comment]
I got this example from the https://github.com/mental32/spotify.py/blob/master/examples/track/get_track_album_artist_user.py

I tried it without the function but thank you, i will try what you told me.

**Comment by mental32** [comment]
The example is correct, read it carefully.

The main function is defined with `async def` this is not the same as a regular function definition.

I'd recommend you follow the [python tutorial](https://docs.python.org/3/tutorial/) and definitely take a look at the [asyncio documentation](https://docs.python.org/3/library/asyncio.html)

**Comment by CipherTheDev** [comment]
Thank you very much,

I will study  asyncio and code my script again.

I'll be closing the issue as i do not want to waste your time but i really appreciated your help :)

Have a good week :)

**Comment by mental32** [comment]
@pastaboy2131 You can join the discord listed in the readme if you need anymore assistance.
